### ISSUE TITLE
SentientOutpost's expiry changes after some time

### ISSUE THREAD

**Issue by TheRealKamisama** [WFCD/warframe-worldstate-parser#187]
**Summary (short):**

SentientOutpost's expiry changes after some time.

---
**Description:**

When the mission is active, the activation and the expiry will maintain at the current mission's for some time, roughly about 5min, after that they will change to the next missions's activation and expiry.
The original expiry and activation went into the "previous".
I don't think this is normal, they should change to the next mission's after the current mission is expiried. 

---
**Evidence:**
![图片](https://user-images.githubusercontent.com/35005476/76160353-6fe31b80-6164-11ea-9eb1-0ff151be15a1.png)
When the mission is not active(the activation and expiry are the next mission's)

![图片](https://user-images.githubusercontent.com/35005476/76160368-a0c35080-6164-11ea-9d95-dbe8c852d42c.png)
When the mission is active and the activation and expiry are the current mission's

![图片](https://user-images.githubusercontent.com/35005476/76160372-c3556980-6164-11ea-85de-ce1ec5f8136d.png)
After 5min the activation and expiry changed to the next mission's and the original ones went to the "previous"

**Comment by TobiTenno** [comment]
This is due to where I'm getting the data from. What I do when I'm consuming it is I do a min on the raw epoch times and use the earlier for the currently active anomaly and a max to be used when one isn't active. If you take a look at my most recent warframe-hub or, you can see how I do this. 

The issue in changing the structure now is that is need to rename "previous", and I don't want to break that for anyone who is using it.

**Comment by TobiTenno** [comment]
What kind of pattern would you prefer to see?

**Comment by TobiTenno** [comment]
feel free to re-open or post if you have any more input.
