### ISSUE TITLE
Worldstate times incorrect?

### ISSUE THREAD

**Issue by rhit-villencr** [WFCD/warframe-worldstate-parser#503]
When I am grabbing the data for, say, cambionCycle. It seems the timeleft value is incorrect. I may be doing something incorrectly though.

![Screenshot 2024-02-25 145403](https://github.com/WFCD/warframe-worldstate-parser/assets/98123650/e61c5f63-3841-4b27-81f0-ca2b37e0a625)

for further context, this is how I am using the API generally:

![Screenshot 2024-02-25 145403](https://github.com/WFCD/warframe-worldstate-parser/assets/98123650/db912e40-f574-417b-84cd-a801a3cd7a52)

**Comment by TobiTenno** [comment]
Time left is cached. It's the string generated when the initial request for it for that minute was cached.

**Comment by rhit-villencr** [comment]
Using the parser, it seems that everything but Cetus and Cambion Drift looks good. I just updated my version of node to the newest version. How would you recommend I implement the rest API as I am not super fluent in anything js.

Screenshot of data grabbed from API:
![Screenshot 2024-02-25 224417](https://github.com/WFCD/warframe-worldstate-parser/assets/98123650/112fa6ae-71ca-4aea-8529-eae7db6d070b)

**Comment by TobiTenno** [comment]
replace whatever you had in `fetchData` with 
```js
fetch('https://api.warframestat.us/pc/?language=en').then((d) => d.json())
```

the above part would simplify down to....

```js
const ws = await fetch('https://api.warframestat.us/pc/?language=en').then((d) => d.json());
const { cetusCyle: cc } = ws;
returnValue = `Cetus is currently in ${cc.state}\nTime remaining until ${cc.isDay ? 'night' : 'day'}: ${cc.timeLeft}`;
```

that said, i don't recommend using timeLeft in general, because it's generated when the object is generated, either way, so it's not a good way to get the timestamp, you'd be better off using moment to make a "from" timestamp, or one of the various "fromX" utilities in warframe-worldstate-data, like get the diff you need and then pass it into... https://github.com/WFCD/warframe-worldstate-data/blob/master/tools/timeDate.js#L19
